{% set name = "htop" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/htop-dev/htop/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5ffac1949a8daaabcffa659c0964360b5008782aae4dfa7702d2323cfb4f438

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('c') }}
    - make
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - ncurses
    - libnl  # [linux]
  run:
    - ncurses
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - htop --version

about:
  home: https://htop.dev/
  license: GPL-2.0-only
  license_file: COPYING
  summary: htop is an interactive text-mode process viewer for Unix systems. It aims to be a better 'top'
  dev_url: https://github.com/htop-dev/htop/

extra:
  recipe-maintainers:
    - chrisburr
    - keuv-grvl
