{% set name = "htop" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/htop-dev/htop/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4744a3bea279f2a3725ed8e5e35ffd9cb10d66673bf07c8fe21feb3c4661305

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - ncurses
    - libnl  # [linux]
  run:
    - ncurses

test:
  commands:
    - htop --version

about:
  home: https://htop.dev/
  license: GPL-2.0-only
  license_file: COPYING
  summary: htop is an interactive text-mode process viewer for Unix systems. It aims to be a better 'top'
  dev_url: https://github.com/htop-dev/htop/

extra:
  recipe-maintainers:
    - chrisburr
    - keuv-grvl
