{% set name = "htop" %}
{% set version = "3.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/htop-dev/htop/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: edf25ee020a5263ffbef9eef5a8c14392bf74e78b3d5c8bc64d9343dd9a82605

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - pkg-config
  host:
    - ncurses
    - libnl  # [linux]
  run:
    - ncurses
  run_constrained:

test:
  commands:
    - htop --version

about:
  home: https://htop.dev/
  license: GPL-2.0-only
  license_file: COPYING
  summary: htop is an interactive text-mode process viewer for Unix systems. It aims to be a better 'top'
  dev_url: https://github.com/htop-dev/htop/

extra:
  recipe-maintainers:
    - chrisburr
    - keuv-grvl
