{% set name = "htop" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/hishamhm/{{ name }}/archive/{{ version }}.tar.gz
  sha256: fb23275090ee5fb19266384c39c69519c8b3844b8f6444730094949c621197c0

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - automake
    - libtool
    - ncurses 5.9*

  run:
    - ncurses 5.9*

test:
  commands:
    - htop --version

about:
  home: https://github.com/hishamhm/htop/
  license: GPL-2.0
  license_file: COPYING
  summary: htop is an interactive text-mode process viewer for Unix systems. It aims to be a better 'top'

extra:
  recipe-maintainers:
    - keuv-grvl
