appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: hBPu1aylaSa8RFZbHQbHKmiq37YAmbJIf99esSNotdnP4Qes5wZxeg/PyNECbjCbiY+fM5XLdLjvJkJSUPdwrIK7p5uwl97c5+zesj/pX2t82jnPJHJ5kviC9pvvcdVtK+pd3mD4M4PWsCLovuzWbG11jXw7cNuweHblPrk0+vWpXVRHB+6M66vI8a27EmXzsIJfcvVgNJr6BxyL3UAxTvy++XaMoeGt6aRkRHfPVhfb9814Y52XSUg6GEpx6vuZTPdaK3D4sIjWa7dK/WypVtT7xdeDhYksUDXlxD1wneTGSXqX5ACg82M8Td8hwVY30kzvUUg2VtjT7TA9fShSN9a9a81nLdPObhF5VUgYoNQg8i2yAck5zhqtFL7ueHsNzAPFyBEJTJ7IhET6bhEcL88BcmJDjTTlsQeixQ+VjzLMwhIzWV+athofdJPBKu2ZKBFcvkimBizCzK988IqBKvAi2XlVpDT7Z02UvfYh0Eim3sDNOUz78Fdi46qvuj1KJDCqEZGfwtOaAhLGolkuCEA+dC4DaV2rcweYlZwcAFwKNWbFVykmd3TOW7a6+zntZ58yi3aremOt7JhpIOmcfjGPStxs+z6dk4iolQAoGLNL0BllCv5LuhDPPHk1Gqj8+U92UMs7phKcivAu8S6GlwR9omLa+QSj24o+eEA6fac=}
conda_forge_output_validation: true
provider:
  linux_ppc64le: default
  linux_aarch64: default
